### ISSUE TITLE
Problems with pillow version 7.1.1

### ISSUE THREAD

**Issue by bisnow33** [Gregor-Mendel-Institute/aradeepopsis#34]
Hi,
Just to signaling a little problem during the installing process.
I tried your tools using conda installing ( conda env create -f environment.yml ).
Actually by default it doesn't work because it's installing pillow 7.1.1 and you get this error when you run the nextflow script :
https://github.com/python-pillow/Pillow/issues/4543

I solved it by installing pillow 7.0.0

Best

**Comment by phue** [comment]
Hi @bisnow33,

many thanks for reporting the issue, it should now be resolved on the `dev` branch with the following commit https://github.com/Gregor-Mendel-Institute/aradeepopsis/commit/708bb5e49adc6b0fbe708c9a203d2492de527bdb

I did some local tests with the conda profile and it is indeed fixed when pinning `pillow` to version 7.0.0
On a sidenote, the docker container is also not affected (presumably because it was built before `pillow=7.1.1` was released)

**Comment by phue** [comment]
`Pillow=7.1.2` has been released, which resolves the issue
